ingrediente(gelatina).
ingrediente(acucar).
ingrediente(agua).
ingrediente(farinhaDeTrigo).
ingrediente(ovo).
ingrediente(gelatina).
ingrediente(carne).
ingrediente(pipoca).
ingrediente(milho).
ingrediente(ervilha).
ingrediente(cenoura).
ingrediente(batatinha).
ingrediente(hamburger).
ingrediente(oleo).
ingrediente(margarina).
ingrediente(queijo).
ingrediente(presunto).
ingrediente(fermento).
ingrediente(frango).
ingrediente(farinha).
ingrediente(peixe).
ingrediente(alho).
ingrediente(sal).
ingrediente(cebola).
ingrediente(tomate).
ingrediente(banana).
ingrediente(maca).
ingrediente(kiwi).
ingrediente(manga).
ingrediente(uva).
ingrediente(cocoRalado).
ingrediente(leite).
ingrediente(achocolatado).
ingrediente(chocolate).
ingrediente(cereal).
ingrediente(suco).
ingrediente(refrigerante).
ingrediente(cogumelo).
ingrediente(macarrao).
ingrediente(molhoDeTomate).
ingrediente(requeijao).
ingrediente(pera).
ingrediente(salsisicha).
ingrediente(abacaxi).
ingrediente(leiteCondesado).
ingrediente(cremeDeLeite).
ingrediente(amendoim).
ingrediente(mandioca).
ingrediente(aipim).
ingrediente(sorvete).
ingrediente(maracuja).
ingrediente(hortelan).
ingrediente(salsinha).
ingrediente(pimentao).
ingrediente(oregano).
ingrediente(pao).
ingrediente(molhoShoyo).
ingrediente(bacon).
ingrediente(arroz).
ingrediente(feijao).
ingrediente(canela).
ingrediente(limao).
ingrediente(amidoMilho).
ingrediente(biscoitoMaizena).
ingrediente(cafe).
ingrediente(cha).
ingrediente(tempero).
ingrediente(calabresa).
ingrediente(pimenta).
ingrediente(maionese).
ingrediente(ketchup).
ingrediente(mostarda).
ingrediente(linguica).
ingrediente(granulado).
ingrediente(pastaDeAmendoin).
ingrediente(batataPalha).
ingrediente(brocolis).
ingrediente(beringela).
ingrediente(geleia).
ingrediente(mel).